### ISSUE TITLE
register endpoint errror

### ISSUE THREAD

**Issue by aaljaali** [DewaldOosthuizen/article_project1#1]
I'm receiving this error:
 File "/usr/src/app/app.py", line 62, in post
    username = data["username"]
TypeError: 'NoneType' object is not subscriptable
172.18.0.1 - - [13/Jun/2020 08:20:09] "POST /register HTTP/1.1" 500 -

Request:
POST http://localhost:5000/register HTTP/1.1

Content-Type: application/json
{
    "username" : "John",
    "password" : "john123",
    "message" : "message1"
}

**Comment by DewaldOosthuizen** [comment]
You will need to pass in content-type: application/json as a header
![image](https://user-images.githubusercontent.com/13827729/84575655-fab06380-adae-11ea-9c0d-6084c470fe2c.png)

If you don't want to specify content type in the header then you can use        
```data = request.get_json(force=True)``` to force the data to be read as JSON.
